name: Code Quality Check

on:
  push:
    branches:
      - dev

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run flake8
        run: flake8 --max-line-length=88 .
